import React,{useState}from'react';import{BarChart3,Circle,FileText,FolderPlus,Grid2X2,Menu,PieChart,Printer,Settings,SlidersHorizontal,UserRound,X}from'lucide-react';
const summary=[['衣柜','普定',3212,20,3232,6970,49,7019,725,9,734,665,0,665],['','轻居',418,0,418,641,0,641,59,0,59,89,0,89],['','合计',3630,20,3650,7611,49,7660,784,9,793,754,0,754],['橱柜','普定',263,8,271,600,2,602,57,5,62,49,0,49],['','轻居',40,0,40,58,0,58,8,0,8,8,0,8],['','合计',315,8,323,658,2,660,65,5,70,57,0,57]];
const rows=Array.from({length:27},(_,i)=>{const n=`EF${60825+Math.floor(i/7)}`;return[n,`${n}${String(i%7+1).padStart(2,'0')}`,i<11?'1015':'1020',i<11?'贵州区域':'河南区域',i<11?'1010166':'1010455','【轻居定制】区域经销商','铜仁市碧江区河西街道...',i<11?'杨芬芬':'闫珂',`2026-07-28 09:${String(32+i).padStart(2,'0')}:31`,'','衣柜','轻居','客单']});
export default function CustomSalesReport({onBack}:{onBack:()=>void}){const[tab,setTab]=useState<'summary'|'detail'>('summary'),[expanded,setExpanded]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState('');const action=(x:string)=>{setToast(x);setTimeout(()=>setToast(''),1800)};return <div className="ioc-shell custom-sales"><header className="topbar"><div className="brand"><span className="brand-latin">QUANU</span><span>全友</span></div><div className="topbar-main"><Menu size={17}/><div className="breadcrumb"><span>首页</span><b>/</b><strong>定制接单打款销售统计报表</strong></div><div className="user-area"><UserRound size={15}/><span>王俊励</span></div></div></header><div className="workspace"><aside className="sidebar"><div className="platform-title">IOC运营平台</div><nav>
  <button className="nav-item"><Grid2X2 size={17}/>我的应用</button>
  <button className="nav-item"><BarChart3 size={17}/>分析看板</button>
  <button className="nav-item menu-active" onClick={()=>setMenu(!menu)}><FileText size={17}/>报表中心</button>
  <button className="nav-item"><PieChart size={17}/>电商运营</button>
  <button className="nav-item"><Settings size={17}/>配置中心</button>
  <button className="nav-item"><Printer size={17}/>导入导出</button>
  <button className="nav-item"><FolderPlus size={17}/>导入</button>
  <button className="nav-item"><SlidersHorizontal size={17}/>自定义报表配置</button>
</nav>{menu&&<div className="report-menu"><b>定制</b><button onClick={onBack}>订单跟踪报表</button><button className="selected" onClick={()=>setMenu(false)}>定制接单打款销售统计报表</button></div>}</aside><main className="main-area"><div className="tabbar"><div className="tab-close"><X size={18}/></div><div className="active-tab"><Circle size={8} fill="currentColor"/>定制接单打款销售统计报表<X size={13}/></div></div><div className="custom-body"><div className="custom-tabs"><button className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}>汇总</button><button className={tab==='detail'?'active':''} onClick={()=>setTab('detail')}>明细</button></div>{tab==='summary'?<Summary action={action}/>:<Detail expanded={expanded} toggle={()=>setExpanded(!expanded)} action={action}/>}</div></main></div><div className="watermark-layer">{Array.from({length:96},(_,i)=><span key={i}>QY-00260959　王俊励　2026-07-28</span>)}</div>{toast&&<div className="toast">{toast}</div>}</div>}
const Actions=({action,reset=false}:{action:(x:string)=>void,reset?:boolean})=><div className="custom-actions"><button onClick={()=>action('查询完成')}>查询</button>{reset&&<button className="secondary" onClick={()=>action('已重置')}>重置</button>}<button onClick={()=>action('导出成功')}>导出</button></div>;
function Summary({action}:{action:(x:string)=>void}){return <><div className="custom-filter"><label>粒度<select><option>日</option></select></label><label>时间<input value="2026-07-28" readOnly/></label><Actions action={action}/></div><div className="custom-table summary"><table><thead><tr><th rowSpan={2}>产品类型</th><th rowSpan={2}>销售类型</th><th colSpan={6}>接单量（截止07/27/24点）</th><th colSpan={6}>接单量（截止07/28/18点）</th></tr><tr>{Array.from({length:12},(_,i)=><th>{['客单单','线上样单','合计'][i%3]}</th>)}</tr></thead><tbody>{summary.map(r=><tr>{r.map((v,i)=><td className={i>1&&i<8?'warm':i>7?'cool':''}>{v}</td>)}</tr>)}</tbody></table></div></>}
function Detail({expanded,toggle,action}:any){const fields=['接单日期','付款日期','产品类型','销售类型','订单类型','客单号','柜子号','办事处','门店'],heads=['客单号','柜子号','办事处编码','办事处名称','经销商编码','经销商描述','门店名称','客户姓名','接单时间','终止时间','产品类型','销售类型','订单类型'];return <><div className={'custom-filter detail '+(expanded?'expanded':'')}>{fields.map((x,i)=><label className={!expanded&&i>3?'hidden':''}>{x}{i<5?<select><option>{i===0?'2026-07-28 - 2026-07-28':'全部'}</option></select>:<input placeholder="请输入"/>}</label>)}<div className="detail-actions"><button className="link" onClick={toggle}>{expanded?'收起':'展开'}</button><Actions action={action} reset/></div></div><div className="custom-table"><table><thead><tr>{heads.map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{r.map(v=><td>{v}</td>)}</tr>)}</tbody></table></div><footer className="custom-page">共 1003 条　50条/页　‹　<b>1</b>　2　3　4　5　…　21　›　前往 1 页</footer></>}
