/** @name 订单跟踪与定制接单打款销售统计报表 */
import React, { useState } from 'react';
import { BarChart3, ChevronDown, Circle, FileText, FolderPlus, Grid2X2, Menu, PieChart, Printer, Settings, SlidersHorizontal, UserRound, X } from 'lucide-react';
import './style.css';

const nav = [['我的应用', Grid2X2], ['分析看板', BarChart3], ['报表中心', FileText], ['电商运营', PieChart], ['配置中心', Settings], ['导入导出', Printer], ['导入', FolderPlus], ['自定义报表配置', SlidersHorizontal]] as const;
const detailRows = Array.from({ length: 25 }, (_, i) => { const no = `EF${60825 + Math.floor(i / 7)}`; return [no, `${no}${String(i % 7 + 1).padStart(2,'0')}`, i < 10 ? '1015' : i < 16 ? '1020' : '1003', i < 10 ? '贵州区域' : i < 16 ? '河南区域' : '河北区域', i < 10 ? '1010166' : '1010455', '【轻居定制】区域经销商', '铜仁市碧江区河西街道...', i < 10 ? '杨芬芬' : '闫珂', `2026-07-28 09:${String(32 + i).padStart(2,'0')}:31`, '2026-07-28', '衣柜', '轻居', '客单']; });
const summary = [['衣柜','普定','3212','20','3232','6970','49','7019','725','9','734','665','0','665'],['','轻居','418','0','418','641','0','641','59','0','59','89','0','89'],['','合计','3630','20','3650','7611','49','7660','784','9','793','754','0','754'],['橱柜','普定','263','8','271','600','2','602','57','5','62','49','0','49'],['','轻居','40','0','40','58','0','58','8','0','8','8','0','8'],['','工程','12','0','12','0','0','0','0','0','0','0','0','0'],['','合计','315','8','323','658','2','660','65','5','70','57','0','57'],['墙板','普定','205','8','213','376','16','392','32','7','39','41','0','41'],['','轻居','10','0','10','12','0','12','1','0','1','1','0','1'],['','合计','215','8','223','388','16','404','33','7','40','42','0','42']];
function App(){const [page,setPage]=useState<'track'|'sales'>('track'); const [tab,setTab]=useState<'summary'|'detail'>('summary'); const [menu,setMenu]=useState(false); const [expanded,setExpanded]=useState(false); const [toast,setToast]=useState(''); const action=(x:string)=>{setToast(x);setTimeout(()=>setToast(''),1800)}; const sales=page==='sales'; return <div className="ioc-shell"><header className="topbar"><div className="brand"><b>QUANU</b><span>全友</span></div><div className="topbar-main"><Menu size={17}/><div className="breadcrumb"><span>首页</span><b>/</b><strong>{sales?'定制接单打款销售统计报表':'订单跟踪报表'}</strong></div><div className="user-area"><UserRound size={14}/><span>王俊励</span><ChevronDown size={14}/></div></div></header><div className="workspace"><aside className="sidebar"><div className="platform-title">IOC运营平台</div><nav>{nav.map(([x,I])=><button className={'nav-item '+(x==='报表中心'&&menu?'active':'')} onClick={()=>x==='报表中心'&&setMenu(!menu)} key={x}><I size={17}/><span>{x}</span></button>)}</nav>{menu&&<div className="report-menu"><b>定制</b><button onClick={()=>{setPage('track');setMenu(false)}}>订单跟踪报表</button><button className={sales?'selected':''} onClick={()=>{setPage('sales');setMenu(false)}}>定制接单打款销售统计报表</button></div>}</aside><main className="main-area"><div className="tabbar"><div className="tab-close"><X size={18}/></div><div className="active-tab"><Circle size={8} fill="currentColor"/><span>{sales?'定制接单打款销售统计报表':'订单跟踪报表'}</span><X size={13}/></div></div>{sales?<section className="sales-content"><div className="report-tabs"><button className={tab==='summary'?'on':''} onClick={()=>setTab('summary')}>汇总</button><button className={tab==='detail'?'on':''} onClick={()=>setTab('detail')}>明细</button></div>{tab==='summary'?<Summary action={action}/>:<Detail expanded={expanded} setExpanded={setExpanded} action={action}/>}</section>:<Track action={action}/>}</main></div><div className="watermark-layer">{Array.from({length:96},(_,i)=><span key={i}>QY-00260959　王俊励　2026-07-28</span>)}</div>{toast&&<div className="toast">{toast}</div>}</div>}
function Buttons({action}:{action:(x:string)=>void}){return <div className="actions"><button onClick={()=>action('查询完成')}>查询</button><button onClick={()=>action('导出成功，请在导出列表中查看')}>导出</button></div>}
function Summary({action}:{action:(x:string)=>void}){return <><div className="summary-filter"><label>粒度 <select><option>日</option></select></label><label>时间 <input type="date" value="2026-07-28" readOnly/></label><Buttons action={action}/></div><div className="summary-table"><table><thead><tr><th rowSpan={2}>产品类型</th><th rowSpan={2}>销售类型</th><th colSpan={6}>接单量（截止07/27/24点）</th><th colSpan={6}>接单量（截止07/28/18点）</th></tr><tr>{['客单单','线上样单','合计','客单单','线上样单','合计','客单单','线上样单','合计','客单单','线上样单','合计'].map(x=><th>{x}</th>)}</tr></thead><tbody>{summary.map(r=><tr>{r.map((x,i)=><td className={i>1&&i<8?'warm':i>7?'cool':''}>{x}</td>)}</tr>)}</tbody></table></div></>}
function Detail({expanded,setExpanded,action}:{expanded:boolean;setExpanded:(x:boolean)=>void;action:(x:string)=>void}){let f=['接单日期','付款日期','产品类型','销售类型','订单类型','客单号','柜子号','办事处','门店']; return <><div className={'detail-filter '+(expanded?'expanded':'')}>{f.map((x,i)=><label className={!expanded&&i>5?'hidden':''}>{x}{i<5?<select><option>{i===0?'2026-07-28 - 2026-07-28':'全部'}</option></select>:<input placeholder="请输入"/>}</label>)}<div className="detail-actions"><button className="link" onClick={()=>setExpanded(!expanded)}>{expanded?'收起':'展开'}</button><button onClick={()=>action('查询完成')}>查询</button><button className="reset" onClick={()=>action('已重置')}>重置</button><button onClick={()=>action('导出成功，请在导出列表中查看')}>导出</button></div></div><div className="detail-table"><table><thead><tr>{['客单号','柜子号','办事处编码','办事处名称','经销商编码','经销商描述','门店名称','客户姓名','接单时间','终止时间','产品类型','销售类型','订单类型'].map(x=><th>{x}</th>)}</tr></thead><tbody>{detailRows.map(r=><tr>{r.map(x=><td>{x}</td>)}</tr>)}</tbody></table></div><div className="pagination">共 1003 条　<select><option>50条/页</option></select>　‹　<span>1</span>　2　3　4　5　6　…　21　›　 前往 <input value="1" readOnly/> 页</div></>}
function Track({action}:{action:(x:string)=>void}){return <section className="track"><div className="track-filter"><label>订单号 <input placeholder="请输入"/></label><label>接单时间 <input type="date" value="2026-07-22" readOnly/></label><Buttons action={action}/></div><div className="empty-report">订单跟踪报表<br/><small>通过“报表中心”可切换至定制接单打款销售统计报表</small></div></section>}
export default App;
